# Generated by Django 5.2.9 on 2026-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrequest',
            name='last_chat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_chat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
