# Generated by Django 5.2.9 on 2025-12-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_requests', to='portal.technician'),
        ),
    ]
