# Generated by Django 5.2.9 on 2025-12-31 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_publicrequest_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('blocked_until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AbuseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip', 'created_at'], name='portal_abus_ip_dd10f3_idx'), models.Index(fields=['user', 'created_at'], name='portal_abus_user_id_cccf10_idx'), models.Index(fields=['reason', 'created_at'], name='portal_abus_reason_ccb73a_idx')],
            },
        ),
    ]
