# Generated by Django 5.2.9 on 2026-01-05 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Construim soluții digitale care cresc afaceri', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Suntem Vertix – partenerul tău în dezvoltare software, automatizări și soluții digitale moderne.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('story_title', models.CharField(default='Povestea noastră', max_length=120)),
                ('story_text', models.TextField(blank=True)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Misiune', max_length=80)),
                ('mission_text', models.TextField(blank=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('vision_title', models.CharField(default='Viziune', max_length=80)),
                ('vision_text', models.TextField(blank=True)),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('values_title', models.CharField(default='Valori', max_length=80)),
                ('values_text', models.TextField(blank=True, help_text='Folosește linii separate, una pe rând (ex: Transparență)')),
                ('values_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('differentiators_title', models.CharField(default='Ce ne diferențiază', max_length=120)),
                ('differentiators_text', models.TextField(blank=True, help_text='Folosește linii separate, una pe rând')),
                ('differentiators_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('cta_title', models.CharField(default='Ai un proiect sau o idee?', max_length=160)),
                ('cta_text', models.CharField(blank=True, default='Hai să discutăm și să găsim varianta potrivită pentru tine.', max_length=240)),
                ('cta_button_text', models.CharField(default='Contactează-ne', max_length=40)),
                ('cta_button_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('tone', models.CharField(choices=[('CORPORATE', 'Corporate'), ('FRIENDLY', 'Prietenos'), ('PREMIUM', 'Premium')], default='FRIENDLY', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PopUpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('style', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_preset', models.BooleanField(default=False)),
                ('preset_key', models.CharField(blank=True, max_length=60)),
                ('show_once_per_browser', models.BooleanField(default=True)),
                ('show_on_home_only', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short', models.CharField(blank=True, max_length=260)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Ex: bi bi-gear, bi bi-robot, bi bi-wrench', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_enabled', models.BooleanField(default=True)),
                ('about_enabled', models.BooleanField(default=True)),
                ('services_enabled', models.BooleanField(default=True)),
                ('projects_enabled', models.BooleanField(default=True)),
                ('industries_enabled', models.BooleanField(default=True)),
                ('contact_enabled', models.BooleanField(default=True)),
                ('blog_enabled', models.BooleanField(default=True)),
                ('careers_enabled', models.BooleanField(default=True)),
                ('gdpr_enabled', models.BooleanField(default=True)),
                ('cookies_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.blogpost')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('availability', models.CharField(choices=[('IN_STOCK', 'În stoc'), ('ORDER', 'La comandă'), ('LEAD_TIME', 'Lead time'), ('OUT', 'Indisponibil')], default='ORDER', max_length=20)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.productcategory')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.industry')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
