# Generated by Django 5.2.9 on 2026-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='short',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
