# Generated by Django 5.2.9 on 2025-12-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service_icon_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Construim soluții digitale care cresc afaceri', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Suntem Vertix – partenerul tău în dezvoltare software, automatizări și soluții digitale moderne.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('story_title', models.CharField(default='Povestea noastră', max_length=120)),
                ('story_text', models.TextField(blank=True)),
                ('mission_title', models.CharField(default='Misiune', max_length=80)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_title', models.CharField(default='Viziune', max_length=80)),
                ('vision_text', models.TextField(blank=True)),
                ('values_title', models.CharField(default='Valori', max_length=80)),
                ('values_text', models.TextField(blank=True, help_text='Folosește linii separate, una pe rând (ex: Transparență)')),
                ('differentiators_title', models.CharField(default='Ce ne diferențiază', max_length=120)),
                ('differentiators_text', models.TextField(blank=True, help_text='Folosește linii separate, una pe rând')),
                ('cta_title', models.CharField(default='Ai un proiect sau o idee?', max_length=160)),
                ('cta_text', models.CharField(blank=True, default='Hai să discutăm și să găsim varianta potrivită pentru tine.', max_length=240)),
                ('cta_button_text', models.CharField(default='Contactează-ne', max_length=40)),
                ('cta_button_url', models.CharField(default='/contact/', max_length=200)),
                ('tone', models.CharField(choices=[('CORPORATE', 'Corporate'), ('FRIENDLY', 'Prietenos'), ('PREMIUM', 'Premium')], default='FRIENDLY', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
