# Generated by Django 5.2.9 on 2025-12-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='cta_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='differentiators_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mvv_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
