# Generated by Django 5.2.9 on 2025-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutpage_cta_image_aboutpage_differentiators_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='mvv_image',
            new_name='mission_image',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
