# Generated by Django 5.2.9 on 2025-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_mvv_image_aboutpage_mission_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('style', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_preset', models.BooleanField(default=False)),
                ('preset_key', models.CharField(blank=True, max_length=60)),
                ('show_once_per_browser', models.BooleanField(default=True)),
                ('show_on_home_only', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
