# Generated by Django 5.2.9 on 2025-12-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='visitor_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
