# Generated by Django 5.2.9 on 2026-01-05 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('docx_template', models.FileField(blank=True, null=True, upload_to='doc_templates/docx/')),
                ('html_template', models.TextField(blank=True)),
                ('series', models.CharField(default='DOC', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('CANCELLED', 'Anulat')], default='DRAFT', max_length=12)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated_docs/docx/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_docs/pdf/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
        ),
    ]
