# Generated by Django 5.2.9 on 2026-01-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_client_user_document_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(default='Termeni și condiții', max_length=200)),
                ('body_html', models.TextField(help_text='HTML permis (paragrafe, liste). Se va afișa ca pagina 2.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termeni document',
                'verbose_name_plural': 'Termeni documente',
            },
        ),
        migrations.AddField(
            model_name='documenttype',
            name='terms',
            field=models.ForeignKey(blank=True, help_text="Dacă e setat, pagina 2 va folosi acești termeni. Dacă nu, folosește 'default'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='documents.documentterms'),
        ),
    ]
